spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/zzfw_cloud?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10000Mb
      max-request-size: 100000Mb
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.attackme.myuploader.model
upload:
  path: C:\BigFile\upload\